In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving superstore raw.csv to superstore raw.csv

In [ ]:
import os

print(os.getcwd())
print(os.listdir())

/content
['.config', 'superstore raw.csv', 'sample_data']

In [ ]:
df=pd.read_csv('superstore raw.csv')

In [ ]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', 'Record_Count', 'Order.Date', 'Order.ID',
       'Order.Priority', 'Product.ID', 'Product.Name', 'Profit', 'Quantity',
       'Region', 'Row.ID', 'Sales', 'Segment', 'Ship.Date', 'Ship.Mode',
       'Shipping.Cost', 'State', 'Sub.Category', 'Year', 'Market2', 'weeknum',
       'Month', 'Month_Name', 'quarter', 'ShippingDays', 'Profit_Margin'],
      dtype='object')

In [ ]:
df.rename(columns={
    "记录数":"Record_Count"
}, inplace=True)

In [ ]:
df.head(20)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,Record_Count,Order.Date,Order.ID,...,State,Sub.Category,Year,Market2,weeknum,Month,Month_Name,quarter,ShippingDays,Profit_Margin
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,California,Paper,2011,North America,2,1,January,1,2,49.111579
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,California,Paper,2011,North America,4,1,January,1,5,48.909474
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,California,Paper,2011,North America,32,8,August,3,4,46.865714
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,California,Paper,2011,North America,32,8,August,3,4,47.982703
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,California,Paper,2011,North America,40,9,September,3,4,51.840000
5,Office Supplies,Los Angeles,United States,JF-154904,Jeremy Farry,0.0,US,1,2011-10-19,CA-2011-117317,...,California,Paper,2011,North America,43,10,October,4,0,50.658462
6,Office Supplies,Los Angeles,United States,WB-218504,William Brown,0.0,US,1,2011-11-04,CA-2011-125829,...,California,Paper,2011,North America,45,11,November,4,7,49.111579
7,Office Supplies,Los Angeles,United States,JA-159704,Joseph Airdo,0.0,US,1,2011-11-12,CA-2011-151295,...,California,Paper,2011,North America,46,11,November,4,4,48.836667
8,Office Supplies,Los Angeles,United States,SP-209204,Susan Pistek,0.0,US,1,2011-11-22,CA-2011-135090,...,California,Paper,2011,North America,48,11,November,4,4,44.850000
9,Office Supplies,Los Angeles,United States,RL-196154,Rob Lucas,0.0,US,1,2011-12-05,CA-2011-133830,...,California,Paper,2011,North America,50,12,December,4,5,47.115102
10,Office Supplies,Los Angeles,United States,KD-163454,Katherine Ducich,0.0,US,1,2011-12-13,CA-2011-113579,...,California,Paper,2011,North America,51,12,December,4,2,46.122667
11,Office Supplies,Los Angeles,United States,JM-161954,Justin MacKendrick,0.0,US,1,2012-02-15,CA-2012-116092,...,California,Paper,2012,North America,7,2,February,1,3,49.329231
12,Office Supplies,Los Angeles,United States,JM-161954,Justin MacKendrick,0.0,US,1,2012-02-15,CA-2012-116092,...,California,Paper,2012,North America,7,2,February,1,3,49.111579
13,Office Supplies,Los Angeles,United States,RD-195854,Rob Dowd,0.0,US,1,2012-02-16,CA-2012-121776,...,California,Paper,2012,North America,7,2,February,1,5,46.796757
14,Office Supplies,Los Angeles,United States,AB-101654,Alan Barnes,0.0,US,1,2012-03-28,CA-2012-131534,...,California,Paper,2012,North America,13,3,March,1,5,48.581818
15,Office Supplies,Los Angeles,United States,AR-105404,Andy Reiter,0.0,US,1,2012-04-11,US-2012-136987,...,California,Paper,2012,North America,15,4,April,2,3,45.791698
16,Office Supplies,Los Angeles,United States,LH-171554,Logan Haushalter,0.0,US,1,2012-06-19,CA-2012-121965,...,California,Paper,2012,North America,25,6,June,2,4,51.840000
17,Office Supplies,Los Angeles,United States,AR-105104,Andrew Roberts,0.0,US,1,2012-08-31,CA-2012-112319,...,California,Paper,2012,North America,35,8,August,3,5,48.264828
18,Office Supplies,Los Angeles,United States,NG-184304,Nathan Gelder,0.0,US,1,2012-11-22,CA-2012-137708,...,California,Paper,2012,North America,47,11,November,4,3,47.924211
19,Office Supplies,Los Angeles,United States,NG-184304,Nathan Gelder,0.0,US,1,2012-11-22,CA-2012-137708,...,California,Paper,2012,North America,47,11,November,4,3,44.790698

In [ ]:
#check the missing values
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
#check the duplicate values
df.duplicated().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [ ]:
#DataType Convesion
df['Order.Date']=pd.to_datetime(df['Order.Date'])
df['Ship.Date']=pd.to_datetime(df['Ship.Date'])

In [ ]:
#column clean up
df.columns=df.columns.str.strip()

In [ ]:
#Feature Engineering
df['Month']=df['Order.Date'].dt.month
df['Month_Name']=df['Order.Date'].dt.month_name()
df['quarter']=df['Order.Date'].dt.quarter
df['ShippingDays']=(df['Ship.Date']-df['Order.Date']).dt.days
df['Profit_Margin']=(df['Profit'] / df['Sales']) * 100

In [ ]:
df[['Month','Month_Name','quarter','Profit_Margin']]

       Month Month_Name  quarter  Profit_Margin
0          1    January        1      49.111579
1          1    January        1      48.909474
2          8     August        3      46.865714
3          8     August        3      47.982703
4          9  September        3      51.840000
...      ...        ...      ...            ...
51285     12   December        4      32.714783
51286     12   December        4      35.093333
51287     12   December        4      35.670000
51288     12   December        4      37.700000
51289     12   December        4      33.651818

[51290 rows x 4 columns]

In [ ]:
#save cleaned data
df.to_csv('cleaned.csv',index=False)

In [ ]:
df.to_csv(
    "sales_mysql.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
from google.colab import files
files.download('cleaned.csv')

# Data Cleaning Summary

The Global Superstore dataset was cleaned and prepared for analysis.

Cleaning activities performed:

1. Removed leading and trailing spaces from column names.
2. Checked for missing values and handled them appropriately.
3. Checked for duplicate records.
4. Converted date columns to datetime format.
5. Created additional date-related columns such as Year, Month, and Quarter.
6. Verified data types for numerical and categorical fields.
7. Standardized column formatting where required.
8. Exported the cleaned dataset for SQL analysis, EDA, and dashboard development.

Outcome:

The dataset is now clean, consistent, and ready for further analysis and visualization.

In [ ]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000